"""Replay log parser for uart_log_tool.

This module parses text log lines generated by uart_log_tui.py and converts
them to replayable records.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from uart_log_protocol import Event

_EVENT_LINE_RE = re.compile(
    r"^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}\.\d{3}) "
    r"mode=(?P<mode>[A-Z]+) "
    r"seq=0x(?P<seq>[0-9A-Fa-f]{2}) "
    r"src=0x(?P<src>[0-9A-Fa-f]{2}) "
    r"evt=0x(?P<evt>[0-9A-Fa-f]{2}) "
    r"ts=(?P<ts>\d+) "
    r"arg0=0x(?P<arg0>[0-9A-Fa-f]{8}) "
    r"arg1=0x(?P<arg1>[0-9A-Fa-f]{8}) "
    r"arg2=0x(?P<arg2>[0-9A-Fa-f]{8}) "
    r"crc=(?P<crc>[A-Z]+) "
    r"lost=(?P<lost>\d+) "
    r"msg=(?P<msg>.*)$"
)


@dataclass(frozen=True)
class ReplayRecord:
    """One replayable event row parsed from a .log line."""

    host_time: str
    seq: int
    event: Event
    lost_count: int


def parse_replay_line(line: str) -> ReplayRecord | None:
    """Parse one tool log line into ReplayRecord.

    Returns None for non-event lines (e.g., META lines).
    """

    match = _EVENT_LINE_RE.match(line.strip())
    if not match:
        return None

    event = Event(
        src_id=int(match.group("src"), 16),
        event_id=int(match.group("evt"), 16),
        timestamp=int(match.group("ts"), 10),
        arg0=int(match.group("arg0"), 16),
        arg1=int(match.group("arg1"), 16),
        arg2=int(match.group("arg2"), 16),
    )

    return ReplayRecord(
        host_time=match.group("time"),
        seq=int(match.group("seq"), 16),
        event=event,
        lost_count=int(match.group("lost"), 10),
    )


def load_replay_records(path: str | Path) -> list[ReplayRecord]:
    """Load all replayable event records from a log file."""

    records: list[ReplayRecord] = []
    replay_path = Path(path)

    with replay_path.open("r", encoding="utf-8") as fp:
        for line in fp:
            rec = parse_replay_line(line)
            if rec is not None:
                records.append(rec)

    return records
