// File list for ModelSim compilation (relative to 03_sim)
+incdir+..\01_src
+incdir+..\02_tb
+define+SIM

..\02_tb\tb_log_pkg.sv
..\02_tb\uart\uart_monitor_pkg.sv
..\01_src\ethernet\eth_udp_reg_pkg.sv
..\01_src\uart_log_cli\uart_log_cli_pkg.sv
..\02_tb\ethernet\eth_udp_reg_tb_pkg.sv
..\02_tb\ethernet\eth_udp_frame_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_bar0_mmio_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_queue_ctrl_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_queue_ctrl_cdc_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_rx_dma_min_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_tx_dma_min_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_bridge_int_tb_pkg.sv
..\02_tb\pcie_dma_eth_l2\pcie_bridge_system_tb_pkg.sv
..\02_tb\pcie_tlp\pcie_tlp_tb_pkg.sv
..\02_tb\uart_log_cli\uart_log_cli_tb_pkg.sv
..\02_tb\uart_log_pcie_ep\uart_log_pcie_ep_tb_pkg.sv
..\02_tb\uart_log_pcie_ep_sts\uart_log_pcie_ep_sts_tb_pkg.sv
..\02_tb\wishbone\wishbone_if.sv
..\02_tb\wishbone\wishbone_driver.sv
..\02_tb\wishbone\wishbone_monitor.sv
..\02_tb\uart\uart_if.sv
..\02_tb\uart\uart_driver.sv
..\02_tb\uart\uart_receiver.sv
..\02_tb\uart\uart_monitor.sv
..\02_tb\pcie_tlp\pcie_tlp_monitor.sv
..\02_tb\pcie_tlp\pcie_tlp_tx_monitor.sv

..\01_src\indexed_reg_access\indexed_reg_pkg.sv
..\01_src\indexed_reg_access\indexed_reg_hub.sv
..\01_src\indexed_reg_access\indexed_reg_test_block.sv
..\01_src\sync_fifo_ae_af.sv
..\01_src\ethernet\eth_async_fifo.sv
..\01_src\ethernet\eth_gray_count_cdc.sv
..\01_src\ethernet\eth_frame_cdc.sv
..\01_src\ethernet\eth_tx_frame_cdc.sv
..\01_src\ethernet\reg_bank.sv
..\01_src\ethernet\reg_access_engine.sv
..\01_src\ethernet\net_cfg_manager.sv
..\01_src\ethernet\eth_mac_ctrl_sync.sv
..\01_src\ethernet\eth_mdio_master.sv
..\01_src\ethernet\rtl8211_mdio_init.sv
..\01_src\ethernet\eth_mac_if.sv
..\01_src\ethernet\eth_rx_parser.sv
..\01_src\ethernet\arp_engine.sv
..\01_src\ethernet\ipv4_rx_parser.sv
..\01_src\ethernet\udp_rx_parser.sv
..\01_src\ethernet\udp_tx_builder.sv
..\01_src\ethernet\ipv4_tx_builder.sv
..\01_src\ethernet\eth_tx_builder.sv
..\01_src\ethernet\eth_log_event_arbiter.sv
..\01_src\ethernet\udp_log_stream_builder.sv
..\01_src\ethernet\eth_diag_tx.sv
..\01_src\ethernet\eth_debug_source.sv
..\01_src\ethernet\eth_subsystem.sv
..\01_src\pcie\pcie_tlp_receiver.sv
..\01_src\pcie\pcie_tlp_transmitter.sv
..\01_src\pcie_dma_eth_l2\pcie_dma_eth_l2_pkg.sv
..\01_src\pcie_dma_eth_l2\pcie_dma_eth_desc_pkg.sv
..\01_src\pcie_eth_l2\pcie_eth_word_bsram_sdp.sv
..\01_src\pcie_eth_l2\pcie_eth_l2_bridge.sv
..\01_src\pcie_dma_eth_l2\pcie_bar0_core_50m.sv
..\01_src\pcie_dma_eth_l2\pcie_bar0_mmio.sv
..\01_src\pcie_dma_eth_l2\pcie_queue_ctrl.sv
..\01_src\pcie_dma_eth_l2\pcie_tlp_mem_rd64_req.sv
..\01_src\pcie_dma_eth_l2\pcie_tlp_cpld_16b_parser.sv
..\01_src\pcie_dma_eth_l2\pcie_tlp_cpld_data_parser.sv
..\01_src\pcie_dma_eth_l2\pcie_tlp_mem_wr64_pkt.sv
..\01_src\pcie_dma_eth_l2\pcie_rx_frame_capture.sv
..\01_src\pcie_dma_eth_l2\pcie_rx_dma_min.sv
..\01_src\pcie_dma_eth_l2\pcie_tx_dma_min.sv
..\01_src\pcie_dma_eth_l2\pcie_tlp_tx_arbiter.sv
..\01_src\pcie_dma_eth_l2\pcie_req_status_cdc.sv
..\01_src\pcie_dma_eth_l2\pcie_queue_ctrl_cdc.sv
..\01_src\reset_mng.sv
..\01_src\uart_lite\uart_rx_stream.sv
..\01_src\uart_lite\uart_tx_stream.sv
..\01_src\uart_log_cli\uart_log_tap.sv
..\01_src\uart_log_cli\uart_log_dual_tap.sv
..\01_src\uart_log_cli\uart_log_cli_evt_fifo.sv
..\01_src\uart_log_cli\uart_log_pcie_ep_cdc_fifo.sv
..\01_src\uart_log_cli\uart_log_pcie_ep.sv
..\01_src\uart_log_cli\uart_log_pcie_ep_sts.sv
..\01_src\uart_log_cli\uart_log_testsrc1.sv
..\01_src\uart_log_cli\uart_log_cli.sv
..\01_src\uart_lite\uart_lite.sv
..\01_src\uart_lite\uart_lite_fifo.sv
..\01_src\uart_lite\uart_lite_fifo_loopback.sv
..\01_src\tangmega60k_dev.sv
..\01_src\tangmega60k_top.sv
